version: '3.8'
services:
  db:
    image: mysql:8.2.0
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3307:3306"
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"